services:
  trmnl-immich-stats:
    image: martynvandijke/trmnl-immich-stats:latest
    container_name: trmnl-immich-stats
    environment:
     - IMMICH_URL=https://immich.example.com
     - IMMICH_API_KEY=change-me
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 10s
      retries: 3
    restart: always
